export const EXPLORING_PROFILES = [
  {
    id: 'investor',
    icon: 'fa-chart-line',
    title: 'Investor',
    description: 'Explore high-growth opportunities, market insights and long-term value.',
    href: '/investment-opportunities',
    accent: '#f0c05a',
    image: '/img/exploring/investor.jpg',
  },
  {
    id: 'end-user',
    icon: 'fa-house',
    title: 'End Users',
    description: 'Find your perfect home with lifestyle, comfort and community.',
    href: '/listings',
    accent: '#e05a9a',
    image: '/img/exploring/end-users.jpg',
  },
  {
    id: 'nri',
    icon: 'fa-globe',
    title: 'NRIs',
    description: 'Invest with confidence, stay connected to your future.',
    href: '/nri-corner',
    accent: '#2dd4bf',
    image: '/img/exploring/nri.jpg',
  },
  {
    id: 'dubai',
    icon: 'fa-plane-departure',
    title: 'Come to Dubai',
    description: 'Experience the lifestyle, explore the city, and find your next chapter.',
    href: '/city?city=dubai',
    accent: '#3b82f6',
    image: '/img/exploring/dubai.jpg',
  },
];
