export const EXPLORING_PROFILES = [
  {
    id: 'investor',
    icon: 'fa-chart-line',
    title: 'Investor',
    description: 'ROI-focused projects, rental yield & capital appreciation.',
    href: '/investment-opportunities',
    accent: '#c9a962',
    glow: 'rgba(201, 154, 98, 0.45)',
  },
  {
    id: 'end-user',
    icon: 'fa-house-user',
    title: 'End Users',
    description: 'Buy your home in India — flats, villas & RERA-verified projects.',
    href: '/listings',
    accent: '#e879a9',
    glow: 'rgba(232, 121, 169, 0.38)',
  },
  {
    id: 'nri',
    icon: 'fa-earth-asia',
    title: 'NRIs',
    description: 'Remote buying, NRI loans & end-to-end support from abroad.',
    href: '/nri-corner',
    accent: '#34d399',
    glow: 'rgba(52, 211, 153, 0.35)',
  },
  {
    id: 'dubai',
    icon: 'fa-plane-departure',
    title: 'Come to Dubai',
    description: 'UAE freehold, Marina living & global investment opportunities.',
    href: '/city?city=dubai',
    accent: '#5eb8ff',
    glow: 'rgba(94, 184, 255, 0.4)',
  },
];
